### ISSUE TITLE
Artworks are marked as modified after restart when "Restore last session on startup" is set

### ISSUE THREAD

**Issue by velmafia** [ribtoks/xpiks#734] opened 2019-07-03 13:53 UTC
When `Restore last session on startup` is set, and `xpisk` is closed with open folder, then in next `xpiks` run all opened artworks are set as `modified`.

branch: current master (2244e4a890095df89a44ab0f4f604fbd8b8350a3), debug and release.
logs before restart:  [before-restart.log](https://github.com/ribtoks/xpiks/files/3355262/before-restart.log)
logs after restart: [after-restart.log](https://github.com/ribtoks/xpiks/files/3355263/after-restart.log)

![modified-after-restart](https://user-images.githubusercontent.com/5277222/60596919-3f173f00-9daa-11e9-9859-889f925612b3.gif)

**Comment by ribtoks** [comment] 2019-07-03 14:45
I cannot reproduce this on master on macOS. Can you check if you can repro it with official 1.5.3 AppImage?

**Comment by ribtoks** [comment] 2019-07-03 14:55
Also nothing special in the logs. Usually such issues happen because of the differences in thread scheduling which means there's a race condition in code. If you will verify that the same happens in AppImage we'll have to debug it thoroughly.

**Comment by velmafia** [comment] 2019-07-03 14:57
This problem doesn't occur on official 1.5.3 AppImage.

Later I will check this issue also on my second PC.

**Comment by ribtoks** [comment] 2019-07-03 15:07
OK, I guess I found your issue:
```
15:36:28.140 debug T#22863 Maintenance::discoverExiftool - File "/home/oborski/code/xpiks/src/xpiks-common/../xpiks-qt/deps/exiftool/exiftool" does not exist
```
Second time when Xpiks starts what you get is that all metadata is only read from your local `metadatacache.db` and actual metadata from files cannot be read because `exiftool` cannot be found.

You run script `./scripts/deploy/update_exiftool.sh` from repo root.

**Comment by ribtoks** [comment] 2019-07-03 16:26
Closing as "works as expected"

**Closed by ribtoks** 2019-07-03 16:26 UTC

**Comment by velmafia** [comment] 2019-07-03 17:58
I have the same behavior on my second PC, and this script solve this problem.

But I have another question, if root case of this behavior is missing `exiftool`, so why I'm able to open this files first time with all metadata? Before this test, I remove all data from configuration directory (`.local/share/Xpiks`), so local cache was empty. I don't run this script before, but still I was able to normally work with `xpisk` with my photos all the time, using system `exiftool` (from `after-restart.log`):
``` 
15:36:56.761 info T#23108 Maintenance::discoverExiftool - Exiftool version: "11.16\n"
```
For me, problem occurs only when I run `xpisk` with open directory. Everything what I open later, are open normally, so I think missing `exiftool` is not real root case.

Also before I opened this issue, I made a lot of test this behavior (initially I was think that problem was related with my changes), and 2 or 3 times "problem" not occurred. I think the root case of this problem is that artworks are opened before available `exiftool` is found.

**Comment by ribtoks** [comment] 2019-07-03 18:06
Xpiks tries to detect exiftool (it might fallback to `/usr/local/bin/exiftool` etc.). Initial launch with restore session has not enough time to detect exiftool so Xpiks reads from cache.

Yes, it still reads from cache because there are several caches. For debug it's `.local/share/Xpiks_debug/${git-branch-name}` or something like that. Also if you switched branch but did not run proper `qmake` then Xpiks will be reading old cache from old branchname
