### ISSUE TITLE
xpiks keeps crashing when I try to apply a preset

### ISSUE THREAD

**Issue by eivanov-bg** [ribtoks/xpiks#535] opened 2018-02-08 17:11 UTC
Steps to reproduce:
- download a fresh installation of xpiks and run it 
- Create one ore more new presets in one ore more new groups (all presets with some random keywords).
- Close xpiks and run it again
- Load a single image without any keywords metadata embedded into it (fresh images, never keyworded before). 
- Try to apply any of the previously created presets - the app crashes immediately.

**Comment by eivanov-bg** [comment] 2018-02-08 17:11
[xpiks-qt-08022018-170102-255.log](https://github.com/ribtoks/xpiks/files/1708052/xpiks-qt-08022018-170102-255.log)
[xpiks-qt-08022018-170214-457.log](https://github.com/ribtoks/xpiks/files/1708053/xpiks-qt-08022018-170214-457.log)
[xpiks-qt-08022018-170016-830.log](https://github.com/ribtoks/xpiks/files/1708054/xpiks-qt-08022018-170016-830.log)

**Comment by ribtoks** [comment] 2018-02-08 17:39
Hi @eivanov-bg 

Thanks for the logs! Unfortunately I couldn't reproduce the issue. Would you be so kind to create a memory dump if you can consistently crash Xpiks?

When Xpiks will crash, don't close it but open Task Manager, right-click Xpiks.exe process and select "Create dump". Then zip it and send it to me please with any viable filesharing. Thanks in advance!

**Comment by ribtoks** [comment] 2018-02-08 17:43
@eivanov-bg Does Xpiks crash if you just add 1 keyword to the file you add? (inside there's no difference between inserting preset and adding 1 keyword

**Comment by eivanov-bg** [comment] 2018-02-08 17:54
When I try the presets it always crashes but sometimes the keywords are saved with the file. When I open the file again and try to clear (from the Clear menu item) the keywords it crashes again. Still crashes if I just type the keywords but this is much stable - I can process 10-20 images before I get an error.

**Comment by ribtoks** [comment] 2018-02-08 17:57
@eivanov-bg It is very weird for it to behave like that. **Please get at least 1 crash dump for me to investigate.** Adding/Clearing keywords and presets - is core functionality, if it would crash for everybody it would be no point in using Xpiks at all. Something is wrong with your installation - e.g. broken download (have you verified the checksum?), antivirus or something else. I need to investigate..

**Comment by eivanov-bg** [comment] 2018-02-08 18:00
https://www.dropbox.com/s/93lkr451u1zznil/Xpiks.zip?dl=0

**Comment by eivanov-bg** [comment] 2018-02-08 18:03
I also tried with disabled antivirus - still the same

**Comment by ribtoks** [comment] 2018-02-08 18:45
@eivanov-bg Thanks for sending me crash dump. I've looked briefly into it. The error appears to happen in the function `DrvSetLayerPaletteEntries()` of `ig9icd64.dll`. The latter is a driver to builtin Intel HD graphics card. Some users have reported [similar issues](https://forums.adobe.com/thread/2252742) for Adobe Illustrator. In their case Intel Graphics driver reinstallation helped to fix the issue. May I ask you to try the same?

**Comment by ribtoks** [comment] 2018-02-08 18:51
@eivanov-bg You can try to set environmental variable `QT_DISABLE_SHADER_DISK_CACHE = 1` as suggested [here](https://bugreports.qt.io/browse/QTBUG-64697?gerritReviewStatus=Open) for a similar issue

**Closed** 2018-02-08 19:21 UTC
Labels: random crash, windows
